name: GoReleaser

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  goreleaser:
    uses: krypsis-io/.github/.github/workflows/goreleaser.yml@main
    secrets:
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
